### ISSUE TITLE
Permissions Issues

### ISSUE THREAD

**Issue by bsmithdx** [dccampbell/php7dev-magento2#1]
FYI I had to ssh into vagrant box as root user and modify permissions in order to get Magento 2 to run.
Process was documented here: http://devdocs.magento.com/guides/v2.0/install-gde/install/file-system-perms.html

**Comment by dccampbell** [comment]
The provision script already follows the permissions outlined by the official docs. Problem was Vagrant runs provision scripts as sudo by default (TIL), so the reindexing at the end of the script was creating root-owned cache and generation folders. Fixed in latest, script no longer runs privileged.
